#!/usr/bin/env bash
# terminates by command name script from task 4 running in an infinite loop on another tty
# is portable: will work if either script is called from another directory
pkill -f ./4-to_infinity_and_beyond
