#!/usr/bin/env bash
# kills by name task 7 script running in an infinite loop on another tty
# is portable: will work if either script is called from another directory
pkill --signal SIGKILL -f ./7-highlander
